services:
  mysql:
    image: "mysql:latest"
    environment:
      - MYSQL_DATABASE=wis
      - MYSQL_USER=wis-db-user
      - MYSQL_PASSWORD=wis-db-pw
      - MYSQL_ROOT_PASSWORD=wis-db-pw
    ports:
      - '3306:3306'

  grafana:
    image: grafana/grafana:10.0.1
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=egualpam
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://grafana:3000/api/health" ]
      interval: 2s
      retries: 30

  # Workaround used to run the init script for the 'grafana' service
  init_grafana:
    image: grafana/grafana:10.0.1
    environment:
      - GRAFANA_USER=admin
      - GRAFANA_PASSWORD=egualpam
    depends_on:
      grafana:
        condition: service_healthy
    volumes:
      - ./grafana:/etc/grafana/init/
      - ./init_grafana.sh:/init_grafana.sh
    working_dir: "/"
    entrypoint: [ "/bin/bash", "-c", "/init_grafana.sh" ]