spring:
  application:
    name: observable-wallet-interaction-service
  datasource:
    url: jdbc:mysql://mysql:3306/wis
    # TODO: Avoid root user from application
    username: root
    password: wis-db-pw
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    defaults:
      enabled: true
      prometheus:
        enabled: true