scrape_configs:
  - job_name: 'backend-kotlin-prometheus'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'backend-kotlin:8080' ]
  - job_name: 'backend-java-prometheus'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'backend-java:8080' ]