{
 "title": "Wallet Interaction Service",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Published events through time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wallet_domain_events_published_total",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Published domain events per second",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(wallet_domain_events_published_total[1m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Infrastructure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "HTTP requests per second",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{uri=~\"/v1/wallets/{wallet-id}|/v1/wallets|/v1/wallets/{wallet-id}/deposit\"}[1m])",
     "legendFormat": "{{method}} {{uri}} {{status}}"
    }
   ]
  },
  {
   "title": "Last 5 deposits persisted",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT d.account_entity_id AS 'Account Id', COUNT(d.id) AS 'Deposits amount'\nFROM (\n  SELECT *\n  FROM wis.deposit\n  ORDER BY created_at DESC\n  LIMIT 5\n) d\nGROUP BY d.account_entity_id\nORDER BY COUNT(d.id) DESC\nLIMIT 5;"
    }
   ]
  }
 ]
}